Repository wecode-bootcamp-korea/24-1st-WoowahanSiblings-frontend, pull requests merged in 2021-09, with the labels that each got.

#8 [24기 김세준] 초기세팅 .vscode/settings.json 파일 추가
  .vscode/settings.json
Labels: Status: 리뷰 요청

#11 [24기 김승찬] Add: footer 구현 완료 피드백 반영 요청
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: Accepted

#1 [24기 김승찬 ] Add : Nav bar 피드백 반영 수정 완료 및 드롭다운 메뉴 추가 구성
  public/data/navmockdata.json
  public/images/ad.webp
  public/images/ad2.webp
  public/images/deli.webp
  public/images/logo2.png
  src/Routes.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavInput.js
  src/components/Nav/NavMenuCategory.js
  src/components/Nav/Navdropmenu.js
  src/components/Nav/TopLayout.js
  src/pages/Main/Main.js
Labels: Status: Accepted

#3 [24기 김승찬] [Main] Add : 라우터 구현을 위해 merge 요청 및 피드백 요청.
  package-lock.json
  package.json
  public/data/instagram.json
  public/data/mock.json
  public/images/1.webp
  public/images/10.jpeg
  public/images/11.jpeg
  public/images/12.jpeg
  public/images/13.jpeg
  public/images/14.jpeg
  public/images/15.jpeg
  public/images/16.jpeg
  public/images/17.jpeg
  public/images/18.jpeg
  public/images/19.jpeg
  public/images/2.webp
  public/images/20.jpeg
  public/images/21.jpeg
  public/images/3.webp
  public/images/4.webp
  public/images/6.jpeg
  public/images/7.jpeg
  public/images/8.jpeg
  public/images/9.jpeg
  public/images/leftbutton.webp
  public/images/leftbuttonx2.webp
  public/images/rightbutton.webp
  public/images/rightbuttonx2.webp
  public/images/스크린샷 2021-08-23 오후 9.09.07.png
  src/Routes.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/components/Nav/TopLayout.js
  src/pages/Main/AdList.js
  src/pages/Main/Benefit.js
  src/pages/Main/ButtonProductList.js
  src/pages/Main/CenterAdd.js
  src/pages/Main/Instagram.js
  src/pages/Main/KulryList.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/ProductList.js
  yarn.lock
Labels: Status: 리뷰 요청

#10 [24기 김세준] Add: 장바구니 페이지 기능 구현, PR 리뷰 및 conflict 해결 완료
  public/data/relatedItem.json
  src/Routes.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/Components/CartItemList.js
  src/pages/Cart/Components/CartItemList.scss
  src/pages/Cart/Components/CartSelect.js
  src/pages/Cart/Components/CartSelect.scss
Labels: Status: Accepted

#5 [24기 이지영] Add: 서버 데이터 통신을 위한 회원가입 기능 1차 구현
  .vscode/settings.json
  src/pages/SignUp/RegExpression.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#14 [24기 김세준] Modify: 상세페이지 장바구니 담기버튼 기능 구현 완료
  src/Routes.js
  src/pages/Detail/Components/CartPut.js
  src/pages/Detail/Components/Related.js
  src/pages/Detail/Components/Related.scss
  src/pages/Detail/Detail.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#12 [24기 이지영] Add: 아이디 중복 체크 기능 구현 완료
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#13 [24기 김승찬 ] Fix : 라우터 기능 추가 및 리팩토링 중
  public/images/10.jpeg
  public/images/11.jpeg
  public/images/12.jpeg
  public/images/13.jpeg
  public/images/14.jpeg
  public/images/15.jpeg
  public/images/16.jpeg
  public/images/17.jpeg
  public/images/6.jpeg
  public/images/7.jpeg
  public/images/8.jpeg
  public/images/9.jpeg
  src/Routes.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.scss
  src/components/Nav/NavMenuCategory.js
  src/components/Nav/Navdropmenu.js
  src/components/Nav/TopLayout.js
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Detail/Components/CartPut.js
  src/pages/Detail/Components/CartPut.scss
  src/pages/Detail/Components/Related.js
  src/pages/Detail/Detail.js
  src/pages/Login/Login.js
  src/pages/Main/AdList.js
  src/pages/Main/Benefit.js
  src/pages/Main/ButtonProductList.js
  src/pages/Main/Instagram.js
  src/pages/Main/KulryList.js
  src/pages/Main/Loading.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/ProductList.js
  src/pages/SignUp/RegExpression.js
  src/pages/SignUp/SignUp.js
Labels: Status: Accepted

#15 [24기 이지영] Modify: 회원가입 페이지 레이아웃 수정
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: Status: 리뷰 요청

#16 [24기 김세준] 마켓컬리 1차 마무리
  src/pages/Cart/Cart.js
  src/pages/Cart/Components/CartItemList.js
  src/pages/Detail/Components/CartPut.js
Labels: Status: 리뷰 요청

#18 [24기 이지영] Modify: input 조건문 색상 변경
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: Status: 리뷰 요청
